<?php

$urlBuilder = $this->getUrlBuilder();
$controllerModule = $this->getControllerModule();
$controllerClassName = $this->getControllerClassName();
$controllerActionName = $this->getControllerActionName();
$mode = ucfirst($this->getMode());
$token = $this->getToken();

?>

<div x-data="{ open: false }"
     class="mgt-developer-toolbar-block mgt-developer-toolbar-block-info">
  <a
      @mouseenter="open = !open"
      @mouseleave="open = !open"
      href="<?php echo $urlBuilder->getUrl('mgtdevelopertoolbar/toolbar/container/execute', ['block' => 'dashboard', 'token' => $token]); ?>">
    <span class="mode"><?php echo $mode; ?></span>
  </a>
  <div class="mgt-developer-toolbar-block-information" x-show="open">
    <ul>
      <li>
         <strong><?php echo __('Mode') ?>:</strong> <?php echo $mode; ?>
      </li>
      <li>
         <strong><?php echo __('Controler Module') ?>:</strong> <?php echo $controllerModule; ?>
      </li>
      <li>
         <strong><?php echo __('Controler Class') ?>:</strong> <?php echo $controllerClassName; ?>
      </li>
      <li>
         <strong><?php echo __('Controler Action Name') ?>:</strong> <?php echo $controllerActionName; ?>
      </li>
    </ul>
  </div>
</div>
